### ISSUE TITLE
Doesn't look fully patched for newest steam release

### ISSUE THREAD

**Issue by myoungh** [mztikk/FF12PCRNGHelper#1]
Hey, grabbed the most recent release with the steam update and the RNG was ticking standing outside Raithwall's Tomb(RNG safe area). So either they messed with the RNG or they messed with the offsets in addition to the base offset.

Thanks for your hard and fast work!

**Comment by Cnnctr** [comment]
Loaded into the same area and it's static. You double-checked the usual culprits like buffs/gambits?

**Comment by myoungh** [comment]
Aha yeah was autoregen on someone ><
