### ISSUE TITLE
PC Game Pass compatibility

### ISSUE THREAD

**Issue by Klaus-Strupper** [mztikk/FF12PCRNGHelper#3]
Hi, I've recently installed the new FFXIITZA using the Xbox Game Pass on PC and noticed that the RNGHelper is not compatible (expected I guess). It's possible to make the Helper work with the game in its Game Pass version?

**Comment by mztikk** [comment]
Since I don't have access to that version its probably not going to happen. But if you're willing to help we can maybe check and try something.

**Comment by hejfelix** [comment]
Ditto here -- what do you need us to check?

**Comment by hejfelix** [comment]
(Also, gamepass is free for a few months currently AFAIK)

**Comment by mztikk** [comment]
> Ditto here -- what do you need us to check?

I'd like to check if the process is generally accessible and if patterns are the same.
Do you have discord and can contact me there? mztikk#7130
